Refactor functions
Talha-Hanif5666/Awesomwbooks-ES6 pull request #1
Opened 2022-12-05 18:15 UTC by Talha-Hanif5666

### **_Highlights_**
 **Add ES6 syntax.
 Change functions to an arrow function.
 Use npm as a software package ages system.
 Import modules.**

2022-12-05 18:39 UTC, DammyShittu requested changes
Hi @Talha-Hanif5666,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 18:39 UTC, DammyShittu commented on modules/content.js
> +        deletebtn.innerHTML = `<button class="btn borders" onclick='deleteItem(${index})'>Remove</button>`;
- [ ] When I click to delete a book the book is not removed from the local storage or the page and I get this error. Kindly fix that.

  ![fkffo](https://user-images.githubusercontent.com/54848363/205715842-134823da-da7b-4c2a-906b-4dfb195bfcd9.jpg)

2022-12-05 18:39 UTC, DammyShittu commented on index.html
> +  <footer id="foots">Copyright &copy; Muhammad Talha Hanif, Amaka Laura & Christian Ani</footer>
- **[OPTIONAL]** I think it would be nice fix the footer to the bottom of the page.

2022-12-06 08:01 UTC, Qoosim approved these changes
#   *Status: Approved* :tada: :heavy_check_mark: 

Hi @Talha-Hanif5666, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-   No linter errors. :heavy_check_mark: 
-   Good README file. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark:

![](https://camo.githubusercontent.com/894d22fdf31aac32d1cd488fc22318df1eea3204fa6d0129c3d61a99f137ce2d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336b75536f3734345549504a6a634a55456e2f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 08:23 UTC, merged